version: '3.8'
name: awsgoo
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "9889:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - blog-a
      - blog-b
    deploy:
      resources:
        limits:
          cpus: '0.025'
          memory: 60M
        reservations:
          cpus: '0.025'
          memory: 50M

  blog-a:
    # build: ../../docker_file/httpd
    build: docker/bloga/
    deploy:
      mode: replicated
      replicas: 6  # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.02'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 100M
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=aws.google.com
      - VIRTUAL_PORT=80
  blog-b:
    # build: ../../docker_file/httpd
    build: docker/blogb/
    deploy:
      mode: replicated
      replicas: 6  # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.02'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 100M
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=google.aws.com
      - VIRTUAL_PORT=80
